Feature/kvis list
Kvissen/Kvissen pull request #44
Opened 2021-10-26 13:07 UTC by niko5297

### Description

Added basic Kvis grid list, showing all kvisses
From there, you can start or edit a kvis

### UI Desktop
![image](https://user-images.githubusercontent.com/43748757/138885119-0c3c82d5-7a94-4a85-a82c-a3188672b522.png)

### UI Mobile
![image](https://user-images.githubusercontent.com/43748757/138885316-2572cdc8-aada-468a-962b-78e6a742ab3d.png)

2021-10-31 13:13 UTC, Logstor requested changes
Det ser godt ud, jeg tror bare lige du har glemt et par ting i farten :smile: :muscle:

2021-10-31 13:13 UTC, Logstor commented on ReactApp/src/components/createKvis/CreateKvisBox.tsx
> +export default function CreateKvisBox({kvis} : {kvis: Kvis}) {
Jeg forstår ikke lige hvorfor du ikke har skrevet:
`export default function CreateKvisBox(kvis: Kvis)`? :smile:

2021-10-31 13:13 UTC, Logstor commented on ReactApp/src/components/kvisList/KvisList.tsx
>  export function KvisList() {
Den her ændring skal stadig laves, da man ellers ikke kan bruge komponenten udefra :smile:

2021-10-31 13:13 UTC, Logstor commented on ReactApp/src/components/kvisList/KvisList.tsx
> +                    kvisses.map((kvis) => {
Lige præcis! :muscle:

2021-10-31 13:13 UTC, Logstor commented on ReactApp/src/components/kvisList/KvisListElement.tsx
> +export default function KvisListElement({kvis} : {kvis: Kvis}) {
Samme spørgsmål som tidligere :smile:

2021-10-31 16:05 UTC, niko5297 commented on ReactApp/src/components/createKvis/CreateKvisBox.tsx
> +export default function CreateKvisBox({kvis} : {kvis: Kvis}) {
Det er ikke tilladt når man arbejder med class og ikke interfaces (sidste jeg prøvede)

2021-10-31 16:05 UTC, niko5297 commented on ReactApp/src/components/kvisList/KvisList.tsx
>  export function KvisList() {
Jeg ved endnu ikke hvad inputtet skal være da vi ikke har besluttet hvordan det skal foregå

2021-10-31 16:06 UTC, niko5297 commented on ReactApp/src/components/kvisList/KvisListElement.tsx
> +export default function KvisListElement({kvis} : {kvis: Kvis}) {
Samme svar som tidligere

2021-11-01 10:53 UTC, Logstor approved these changes
Merge merge :smile:

2021-11-01 12:41 UTC, merged